### PR TITLE
Check underlying permissions per item, not per filesystem root

### PR DESCRIPTION
**Pull request by chewi**
This is what I originally intended in #62 but perhaps it was misunderstood. I have also applied the character set conversion that is done for other native filesystem operations.

### CODE REVIEW

**Comment by chewi** [comment]
I got caught out by this again after an upgrade to a production system. :cry: Please merge it!

**Comment by sjarvela** [comment]
Sorry for delay. I went through this again, and the change seems to be reasonable. But I'll make it a bit different than in the pull-request, I'll let you know when commit has been done.

**Comment by sjarvela** [comment]
Commit: https://github.com/sjarvela/kloudspeaker/commit/b76adc2fe8dfd41ded3cd9f0c230f81508c4b6b3

Actually the only difference is that $item->isWritable() is direct call.

**Comment by chewi** [comment]
That makes sense, thanks!

**Pull request closed without merging**
